export type DecisionAction = "BUY" | "HOLD" | "SELL";

export interface TokenSnapshot {
  token: string;
  symbol: string;
  name: string;
  creator: string;
  creatorPriorLaunches?: number;
  creatorPriorGraduations?: number;
  creatorPriorRugLikeClosures?: number;
  pair: string;
  pairToken0?: string;
  pairToken1?: string;
  quoteToken?: string;
  virtualQuoteReserve?: string;
  createdBlock?: string;
  virtualTokenStart?: string;
  virtualTokenReserve?: string;
  minTokenReserve?: string;
  createdAt: number;
  lastEventAt: number;
  buys: number;
  sells: number;
  buyMon: number;
  sellMon: number;
  progressPct: number;
  progressVelocityPctPerMin?: number;
  creatorInitialBuyMon?: number;
  progressHistory?: Array<{ ts: number; progressPct: number }>;
  graduated: boolean;
  locked: boolean;
  holders: number;
  volumeUsd: number;
  priceUsd: number;
  priceMon: number;
  peakPriceMon: number;
  localScore: number;
  marketType?: "BONDING_CURVE" | "DEX";
  liquidityMon?: number;
  liquidityUsd?: number;
  marketCapMon?: number;
  marketCapUsd?: number;
  monUsdPrice?: number;
  volumeMon?: number;
  changePct?: number;
  athPriceMon?: number;
  athPriceUsd?: number;
  dipPct?: number;
  drawdownFromRecentPeakPct?: number;
  drawdownFromAthPct?: number;
  trendPct1h?: number;
  trendPct4h?: number;
  reboundPct1h?: number;
  buySellRatio5m?: number;
  volume5mMon?: number;
  volumePrev5mMon?: number;
  volumeAcceleration5m?: number;
  dayOpenPriceMon?: number;
  dayHighPriceMon?: number;
  dayLowPriceMon?: number;
  dayAvgPriceMon?: number;
  daySamples?: number;
  distanceFromDayLowPct?: number;
  distanceFromDayAvgPct?: number;
  distanceFromDayHighPct?: number;
  entryStrategy?: "DAILY_MEAN_REVERSION" | "DIP_REVERSION" | "MOMENTUM" | "FLOW" | "HYBRID";
  flowHistory?: Array<{ ts: number; buyMon: number; sellMon: number }>;
  lastMarketAt?: number;
  priceHistory?: Array<{ ts: number; priceMon: number }>;
  watchReason?: string;
  lastCandidateAiAt?: number;
  lastEnrichedAt?: number;
  lastFlowApiAt?: number;
  lastBuyAttemptAt?: number;
  lastBuyTx?: string;
  buyBlockedUntil?: number;
  apiTrend1mPct?: number;
  apiTrend5mPct?: number;
  apiTrend15mPct?: number;
  apiTrend1hPct?: number;
  apiVolume5mUsd?: number;
  apiBuy1mUsd?: number;
  apiSell1mUsd?: number;
  apiBuyTx1m?: number;
  apiSellTx1m?: number;
  apiUniqueBuyers1m?: number;
  apiTopBuyerShare1m?: number;
  apiCreatorBuyShare5m?: number;
  apiBuy5mUsd?: number;
  apiSell5mUsd?: number;
  apiBuyTx5m?: number;
  apiSellTx5m?: number;
  apiBuyMakers5m?: number;
  apiSellMakers5m?: number;
  aiAction?: DecisionAction;
  aiConfidence?: number;
  aiReason?: string;
  entryDiagnostics?: EntryGateDiagnostics;
  entryBlockedUntil?: number;
  lastClosedAt?: number;
}

export interface EntryGateDiagnostics {
  checkedAt: number;
  readyForAi: boolean;
  primary: string;
  blockers: string[];
  metrics: {
    ageMinutes: number;
    liquidityUsd: number;
    marketCapUsd: number;
    holders: number;
    volumeMon: number;
    volumeUsd: number;
    dipPct: number;
    drawdownFromRecentPeakPct: number;
    drawdownFromAthPct: number;
    rebound1hPct: number;
    trend1hPct: number;
    trend4hPct: number;
    dayLowPriceMon: number;
    dayAvgPriceMon: number;
    distanceFromDayLowPct: number;
    distanceFromDayAvgPct: number;
    localScore: number;
  };
  aiAction?: DecisionAction;
  aiConfidence?: number;
}

export interface Position {
  id: string;
  token: string;
  symbol: string;
  amountRaw: string;
  decimals: number;
  entryMon: number;
  entryPriceMon: number;
  currentMon: number;
  realizedPnlMon?: number;
  pnlMon: number;
  pnlPct: number;
  peakMon: number;
  peakPnlPct?: number;
  entryLiquidityUsd?: number;
  profitTake1Done?: boolean;
  profitTake2Done?: boolean;
  profitTake3Done?: boolean;
  strategy?: "DAILY_MEAN_REVERSION" | "DIP_REVERSION" | "MOMENTUM" | "FLOW" | "HYBRID" | "UNKNOWN";
  openedAt: number;
  lastAiAt: number;
  lastAiAction?: DecisionAction;
  lastAiConfidence?: number;
  lastAiReason?: string;
  entryTx: string;
  costBasisKnown?: boolean;
  recoveredAt?: number;
  status: "OPEN" | "CLOSED" | "CLOSING" | "FAILED";
  closeTx?: string;
  closeReason?: string;
  lastSellAttemptAt?: number;
  lastSellTx?: string;
  lastSellFailureAt?: number;
  sellBlockedUntil?: number;
  lastSellError?: string;
  sellFailureCount?: number;
  sellQuarantineUntil?: number;
}

export interface TradeRecord {
  id: string;
  ts: number;
  action: "BUY" | "SELL";
  token: string;
  symbol: string;
  amountMon: number;
  pnlMon?: number;
  pnlPct?: number;
  txHash?: string;
  reason: string;
  score?: number;
  aiConfidence?: number;
}

export interface EquityPoint {
  ts: number;
  balanceMon: number;
  openExposureMon: number;
  unrealizedPnlMon: number;
  equityMon: number;
  realizedPnlMon: number;
}

export interface PendingExecution {
  id: string;
  side: "BUY" | "SELL";
  token: string;
  symbol: string;
  spendMon?: number;
  amountRaw?: string;
  decimals?: number;
  txHash?: string;
  submittedAt?: number;
  stage?: "V1_SELL" | "V2_SELL" | "V2_LVMON_REDEEM" | "V2_WMON_UNWRAP";
  positionId?: string;
  createdAt: number;
}

export interface BotStats {
  aiCalls: number;
  aiDailyCalls?: number;
  aiDailyDay?: string;
  aiFailures: number;
  eventCount: number;
  wins: number;
  losses: number;
  lastProcessedBlock?: string;
  lastCycleAt?: number;
  lastRiskCycleAt?: number;
  lastError?: string;
  lastAiError?: string;
  lastAiFailureAt?: number;
  lastIdleReason?: string;
  dailyRiskDay?: string;
  dailyRiskStartEquityMon?: number;
  dailyRiskDrawdownPct?: number;
  entryCircuitBreakerUntil?: number;
  entryCircuitBreakerReason?: string;
  startedAt?: number;
  lastLogCount?: number;
  lastLogPollAt?: number;
  lastDexLogCount?: number;
  lastDexLogPollAt?: number;
  lastDexProcessedBlock?: string;
  eventBackfillDone?: boolean;
  lastDiscoveryAt?: number;
  discoveredTokens?: number;
  watchedTokens?: number;
  eligibleCandidates?: number;
  lastReconciliationAt?: number;
  recoveredPositions?: number;
  lastScheduledAttemptAt?: number;
  lastScheduledPhase?: string;
  lastScheduledPhaseAt?: number;
  lastScheduledPhaseErrorAt?: number;
  lastScheduledDurationMs?: number;
  lastScheduledError?: string;
}

export interface BotState {
  version: 1;
  running: boolean;
  liveTrading: boolean;
  walletAddress: string;
  balanceMon: number;
  realizedPnlMon: number;
  unrealizedPnlMon: number;
  openExposureMon: number;
  seasonality: Record<string, { buyMon: number; sellMon: number; events: number }>;
  tokens: Record<string, TokenSnapshot>;
  positions: Record<string, Position>;
  trades: TradeRecord[];
  pendingExecutions: Record<string, PendingExecution>;
  equity: EquityPoint[];
  stats: BotStats;
}
